### ISSUE TITLE
2010 %Home Ownership numbers seem very low

### ISSUE THREAD

**Issue by radumas** [codeforboston/ungentry#53]
Across Boston all numbers seem to have lowered dramatically from 2010, even in high ownership areas such as Brookline and Brighton.

**Comment by mjrouser** [comment]
I'm not sure what you mean by "lowered from 2010" since 2010 is our last data point.

Our data was thoroughly analyzed and cleaned by Harvard sociologist @jacks1177.  

In the future, if you would like to open an issue, please make sure it is "dev ready."  Find a data source that supports your claims and prepare it in a way that it could be included in the project.  Or at the very least, link to it in your comment.
