### ISSUE TITLE
Tracts not switching colors with different variables

### ISSUE THREAD

**Issue by alisha** [codeforboston/ungentry#67]
When switching from the default variable to the "% of household income income 0-25k" variable, the Logan airport doesn't switch from the red to the blue color scheme. It switches to grey when the user goes off the screen and back to it.

![screen shot 2015-03-31 at 7 49 41 pm](https://cloud.githubusercontent.com/assets/1406727/6931769/25d2b0be-d7df-11e4-92ad-42f4d64ecc52.png)

**Comment by bouviervj** [comment]
This is probably because no data is linked to this tract for this year.

ungentry/prospect/CensusLayer/js/CensusLayer.js

In those lines 323 327, there probably a parameter that is missing in the default returned color:
return {color: "#7F7F7F", "weight": 0 , "fillOpacity": 0.6};

In a normal situation the we define a "fillcolor" field that is probably not replaced when loading a new data, i.e. the data must be defined to redefined the 'fillcolor' field. I have probably changed the way we switch from a property to an other...

Just try to return in default values a fillcolor with #7F7F7F value (dark gray )

Cheers,
Julien
